language: cpp
os: linux
dist: xenial
addons:
    apt:
        sources:
            - sourceline: 'ppa:zhaofeng-shu33/gtest'
        packages:
            - libgtest-dev
            - lcov

script:
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING=ON -DCODE_COVERAGE=ON ..
    - make
    - ctest

after_success:
    - lcov --directory . --capture --output-file coverage.info
    - lcov -- remove coverage.info '/usr/*' --output-file coverage.info
    - bash <(curl -s https://codecov.io/bash) -f coverage.info
